
-- create
CREATE TABLE CLASSMATES (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (0001, 'Clark', 18, 'Moscow');
INSERT INTO CLASSMATES VALUES (0002, 'Dave', 21, 'Perm');
INSERT INTO CLASSMATES VALUES (0003, 'Ava', 35, 'New York');
INSERT INTO CLASSMATES VALUES (0004, 'Ivan', 35, 'New York');
INSERT INTO CLASSMATES VALUES (0005, 'Vladimir', 55, 'Astana');
INSERT INTO CLASSMATES VALUES (0006, 'Hideo', 33, 'Tokyo');
INSERT INTO CLASSMATES VALUES (0007, 'Ivanka', 19, 'Miami');

-- fetch 
SELECT * FROM CLASSMATES WHERE age < 100;